stages:
  - build
  - deploy

# 缓存 node_modules 和本地 .npm 缓存，加快构建
cache:
  paths:
    - node_modules/
    - .npm/

build-job:
  stage: build
  tags:
    - miniprogram
  script:
    - export APPID=$(node -p "require('./project.config.json').appid")
    - export PROJECT_NAME=$(node -p "require('./project.config.json').projectname")
    - echo "项目信息 AppID=$APPID 项目名称=$PROJECT_NAME"
    - echo "$WX_PRIVATE_KEY" > ./private.$APPID.key
    - echo "私钥文件已生成 private.$APPID.key"
    - echo "安装项目依赖..."
    - npm install
    - echo "构建npm包..."
    - npm run build-npm
    - echo "构建完成，开始上传..."
    - npm run upload
  only:
    - main
    - merge_requests
