stages:
  - build
  - deploy

# 缓存 node_modules 和本地 .npm 缓存，加快构建
cache:
  paths:
    - node_modules/
    - .npm/

build-job:
  stage: build
  tags:
    - miniprogram
  script:
    - echo "$WX_PRIVATE_KEY" > ./private.wx12e1d849722bc528.key
    - echo "安装项目依赖..."
    - npm install
    - echo "构建npm包..."
    - npm run build-npm
    - echo "构建完成，开始上传..."
    - npm run upload
  only:
    - main
    - merge_requests