stages:
  - build
  - deploy

# 全局缓存配置
cache:
  paths:
    - node_modules/

# 安装依赖
build-job:
  stage: build
  tags:
    - build
  script:
    - echo "安装项目依赖..."
    - npm install
    - echo "构建npm包..."
    - npm run build-npm
    - echo "构建完成。开始上传"
    - npm run upload
  only:
    - main
    - merge_requests
